//------------------------------------------------------------------------------
/// <autogenerated>
///     This code was generated by a tool.
///     Runtime Version: 4.0.30319.42000
///
///     Changes to this file may cause incorrect behavior and will be lost if 
///     the code is regenerated.
/// </autogenerated>
//------------------------------------------------------------------------------

//@cc_on
//@set @debug(off)

import System.Xml.Serialization;

//
//This source code was auto-generated by xsd, Version=4.8.3928.0.
//

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fivesqd.com/schemas/veml/2.3") System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3", IsNullable=false) 
class veml {
    
    private var metadataField : vemlMetadata;
    
    private var environmentField : vemlEnvironment;
    
    ///<remarks/>
    public final function get metadata() : vemlMetadata {
        return this.metadataField;
    }
    public final function set metadata(value : vemlMetadata) {
        this.metadataField = value;
    }
    
    ///<remarks/>
    public final function get environment() : vemlEnvironment {
        return this.environmentField;
    }
    public final function set environment(value : vemlEnvironment) {
        this.environmentField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class vemlMetadata {
    
    private var titleField : System.String;
    
    private var capabilityField : System.String[];
    
    private var scriptField : System.String[];
    
    private var inputeventField : inputevent[];
    
    private var controlflagsField : controlflags;
    
    private var synchronizationserviceField : synchronizationservice[];
    
    ///<remarks/>
    public final function get title() : System.String {
        return this.titleField;
    }
    public final function set title(value : System.String) {
        this.titleField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("capability") 
    function get capability() : System.String[] {
        return this.capabilityField;
    }
    public final function set capability(value : System.String[]) {
        this.capabilityField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("script") 
    function get script() : System.String[] {
        return this.scriptField;
    }
    public final function set script(value : System.String[]) {
        this.scriptField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("inputevent") 
    function get inputevent() : inputevent[] {
        return this.inputeventField;
    }
    public final function set inputevent(value : inputevent[]) {
        this.inputeventField = value;
    }
    
    ///<remarks/>
    public final function get controlflags() : controlflags {
        return this.controlflagsField;
    }
    public final function set controlflags(value : controlflags) {
        this.controlflagsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("synchronizationservice") 
    function get synchronizationservice() : synchronizationservice[] {
        return this.synchronizationserviceField;
    }
    public final function set synchronizationservice(value : synchronizationservice[]) {
        this.synchronizationserviceField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class inputevent {
    
    private var inputField : System.String;
    
    private var eventField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get input() : System.String {
        return this.inputField;
    }
    public final function set input(value : System.String) {
        this.inputField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get \event() : System.String {
        return this.eventField;
    }
    public final function set \event(value : System.String) {
        this.eventField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class terrainentitylayer {
    
    private var diffusetextureField : System.String;
    
    private var normaltextureField : System.String;
    
    private var masktextureField : System.String;
    
    private var specularField : System.String;
    
    private var metallicField : float;
    
    private var smoothnessField : float;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("diffuse-texture") 
    function get diffusetexture() : System.String {
        return this.diffusetextureField;
    }
    public final function set diffusetexture(value : System.String) {
        this.diffusetextureField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("normal-texture") 
    function get normaltexture() : System.String {
        return this.normaltextureField;
    }
    public final function set normaltexture(value : System.String) {
        this.normaltextureField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mask-texture") 
    function get masktexture() : System.String {
        return this.masktextureField;
    }
    public final function set masktexture(value : System.String) {
        this.masktextureField = value;
    }
    
    ///<remarks/>
    public final function get specular() : System.String {
        return this.specularField;
    }
    public final function set specular(value : System.String) {
        this.specularField = value;
    }
    
    ///<remarks/>
    public final function get metallic() : float {
        return this.metallicField;
    }
    public final function set metallic(value : float) {
        this.metallicField = value;
    }
    
    ///<remarks/>
    public final function get smoothness() : float {
        return this.smoothnessField;
    }
    public final function set smoothness(value : float) {
        this.smoothnessField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class placementsocket {
    
    private var positionField : position;
    
    private var rotationField : rotation;
    
    private var connectingoffsetField : position;
    
    ///<remarks/>
    public final function get position() : position {
        return this.positionField;
    }
    public final function set position(value : position) {
        this.positionField = value;
    }
    
    ///<remarks/>
    public final function get rotation() : rotation {
        return this.rotationField;
    }
    public final function set rotation(value : rotation) {
        this.rotationField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("connecting-offset") 
    function get connectingoffset() : position {
        return this.connectingoffsetField;
    }
    public final function set connectingoffset(value : position) {
        this.connectingoffsetField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class position {
    
    private var xField : double;
    
    private var yField : double;
    
    private var zField : double;
    
    public function position() {
        this.xField = 0;
        this.yField = 0;
        this.zField = 0;
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get x() : double {
        return this.xField;
    }
    public final function set x(value : double) {
        this.xField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get y() : double {
        return this.yField;
    }
    public final function set y(value : double) {
        this.yField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get z() : double {
        return this.zField;
    }
    public final function set z(value : double) {
        this.zField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class rotation {
    
    private var xField : double;
    
    private var yField : double;
    
    private var zField : double;
    
    private var wField : double;
    
    public function rotation() {
        this.xField = 0;
        this.yField = 0;
        this.zField = 0;
        this.wField = 1;
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get x() : double {
        return this.xField;
    }
    public final function set x(value : double) {
        this.xField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get y() : double {
        return this.yField;
    }
    public final function set y(value : double) {
        this.yField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get z() : double {
        return this.zField;
    }
    public final function set z(value : double) {
        this.zField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get w() : double {
        return this.wField;
    }
    public final function set w(value : double) {
        this.wField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(TypeName="size-percent", Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class sizepercent {
    
    private var xField : double;
    
    private var yField : double;
    
    public function sizepercent() {
        this.xField = 1;
        this.yField = 1;
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get x() : double {
        return this.xField;
    }
    public final function set x(value : double) {
        this.xField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get y() : double {
        return this.yField;
    }
    public final function set y(value : double) {
        this.yField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(TypeName="position-percent", Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class positionpercent {
    
    private var xField : double;
    
    private var yField : double;
    
    public function positionpercent() {
        this.xField = 0;
        this.yField = 0;
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get x() : double {
        return this.xField;
    }
    public final function set x(value : double) {
        this.xField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(0) 
    function get y() : double {
        return this.yField;
    }
    public final function set y(value : double) {
        this.yField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class size {
    
    private var xField : double;
    
    private var yField : double;
    
    private var zField : double;
    
    public function size() {
        this.xField = 1;
        this.yField = 1;
        this.zField = 1;
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get x() : double {
        return this.xField;
    }
    public final function set x(value : double) {
        this.xField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get y() : double {
        return this.yField;
    }
    public final function set y(value : double) {
        this.yField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get z() : double {
        return this.zField;
    }
    public final function set z(value : double) {
        this.zField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class scale {
    
    private var xField : double;
    
    private var yField : double;
    
    private var zField : double;
    
    public function scale() {
        this.xField = 1;
        this.yField = 1;
        this.zField = 1;
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get x() : double {
        return this.xField;
    }
    public final function set x(value : double) {
        this.xField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get y() : double {
        return this.yField;
    }
    public final function set y(value : double) {
        this.yField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(1) 
    function get z() : double {
        return this.zField;
    }
    public final function set z(value : double) {
        this.zField = value;
    }
}

///<remarks/>
public System.Xml.Serialization.XmlIncludeAttribute(canvastransform) System.Xml.Serialization.XmlIncludeAttribute(sizetransform) System.Xml.Serialization.XmlIncludeAttribute(scaletransform) System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class basetransform {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class canvastransform extends basetransform {
    
    private var positionpercentField : positionpercent;
    
    private var sizepercentField : sizepercent;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("position-percent") 
    function get positionpercent() : positionpercent {
        return this.positionpercentField;
    }
    public final function set positionpercent(value : positionpercent) {
        this.positionpercentField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("size-percent") 
    function get sizepercent() : sizepercent {
        return this.sizepercentField;
    }
    public final function set sizepercent(value : sizepercent) {
        this.sizepercentField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class sizetransform extends basetransform {
    
    private var positionField : position;
    
    private var rotationField : rotation;
    
    private var sizeField : size;
    
    ///<remarks/>
    public final function get position() : position {
        return this.positionField;
    }
    public final function set position(value : position) {
        this.positionField = value;
    }
    
    ///<remarks/>
    public final function get rotation() : rotation {
        return this.rotationField;
    }
    public final function set rotation(value : rotation) {
        this.rotationField = value;
    }
    
    ///<remarks/>
    public final function get size() : size {
        return this.sizeField;
    }
    public final function set size(value : size) {
        this.sizeField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class scaletransform extends basetransform {
    
    private var positionField : position;
    
    private var rotationField : rotation;
    
    private var scaleField : scale;
    
    ///<remarks/>
    public final function get position() : position {
        return this.positionField;
    }
    public final function set position(value : position) {
        this.positionField = value;
    }
    
    ///<remarks/>
    public final function get rotation() : rotation {
        return this.rotationField;
    }
    public final function set rotation(value : rotation) {
        this.rotationField = value;
    }
    
    ///<remarks/>
    public final function get scale() : scale {
        return this.scaleField;
    }
    public final function set scale(value : scale) {
        this.scaleField = value;
    }
}

///<remarks/>
public System.Xml.Serialization.XmlIncludeAttribute(waterblockerentity) System.Xml.Serialization.XmlIncludeAttribute(waterentity) System.Xml.Serialization.XmlIncludeAttribute(voxelentity) System.Xml.Serialization.XmlIncludeAttribute(textentity) System.Xml.Serialization.XmlIncludeAttribute(terrainentity) System.Xml.Serialization.XmlIncludeAttribute(lightentity) System.Xml.Serialization.XmlIncludeAttribute(imageentity) System.Xml.Serialization.XmlIncludeAttribute(inputentity) System.Xml.Serialization.XmlIncludeAttribute(buttonentity) System.Xml.Serialization.XmlIncludeAttribute(htmlentity) System.Xml.Serialization.XmlIncludeAttribute(canvasentity) System.Xml.Serialization.XmlIncludeAttribute(characterentity) System.Xml.Serialization.XmlIncludeAttribute(archmeshentity) System.Xml.Serialization.XmlIncludeAttribute(prismmeshentity) System.Xml.Serialization.XmlIncludeAttribute(tetrahedronmeshentity) System.Xml.Serialization.XmlIncludeAttribute(rectangularpyramidmeshentity) System.Xml.Serialization.XmlIncludeAttribute(conemeshentity) System.Xml.Serialization.XmlIncludeAttribute(torusmeshentity) System.Xml.Serialization.XmlIncludeAttribute(planemeshentity) System.Xml.Serialization.XmlIncludeAttribute(cylindermeshentity) System.Xml.Serialization.XmlIncludeAttribute(capsulemeshentity) System.Xml.Serialization.XmlIncludeAttribute(spheremeshentity) System.Xml.Serialization.XmlIncludeAttribute(cubemeshentity) System.Xml.Serialization.XmlIncludeAttribute(meshentity) System.Xml.Serialization.XmlIncludeAttribute(audioentity) System.Xml.Serialization.XmlIncludeAttribute(containerentity) System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class entity {
    
    private var transformField : basetransform;
    
    private var entity1Field : entity[];
    
    private var synchronizerField : System.String;
    
    private var placementsocketField : placementsocket[];
    
    private var tagField : System.String;
    
    private var idField : System.String;
    
    private var onloadeventField : System.String;
    
    ///<remarks/>
    public final function get transform() : basetransform {
        return this.transformField;
    }
    public final function set transform(value : basetransform) {
        this.transformField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("entity") 
    function get entity1() : entity[] {
        return this.entity1Field;
    }
    public final function set entity1(value : entity[]) {
        this.entity1Field = value;
    }
    
    ///<remarks/>
    public final function get synchronizer() : System.String {
        return this.synchronizerField;
    }
    public final function set synchronizer(value : System.String) {
        this.synchronizerField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("placement-socket") 
    function get placementsocket() : placementsocket[] {
        return this.placementsocketField;
    }
    public final function set placementsocket(value : placementsocket[]) {
        this.placementsocketField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get tag() : System.String {
        return this.tagField;
    }
    public final function set tag(value : System.String) {
        this.tagField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get id() : System.String {
        return this.idField;
    }
    public final function set id(value : System.String) {
        this.idField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("on-load-event") 
    function get onloadevent() : System.String {
        return this.onloadeventField;
    }
    public final function set onloadevent(value : System.String) {
        this.onloadeventField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class waterblockerentity extends entity {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class waterentity extends entity {
    
    private var shallowcolorField : System.String;
    
    private var deepcolorField : System.String;
    
    private var specularcolorField : System.String;
    
    private var scatteringcolorField : System.String;
    
    private var deepstartField : float;
    
    private var deependField : float;
    
    private var distortionField : float;
    
    private var smoothnessField : float;
    
    private var numwavesField : float;
    
    private var waveamplitudeField : float;
    
    private var wavesteepnessField : float;
    
    private var wavespeedField : float;
    
    private var wavelengthField : float;
    
    private var wavescaleField : float;
    
    private var waveintensityField : float;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("shallow-color") 
    function get shallowcolor() : System.String {
        return this.shallowcolorField;
    }
    public final function set shallowcolor(value : System.String) {
        this.shallowcolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("deep-color") 
    function get deepcolor() : System.String {
        return this.deepcolorField;
    }
    public final function set deepcolor(value : System.String) {
        this.deepcolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("specular-color") 
    function get specularcolor() : System.String {
        return this.specularcolorField;
    }
    public final function set specularcolor(value : System.String) {
        this.specularcolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("scattering-color") 
    function get scatteringcolor() : System.String {
        return this.scatteringcolorField;
    }
    public final function set scatteringcolor(value : System.String) {
        this.scatteringcolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("deep-start") 
    function get deepstart() : float {
        return this.deepstartField;
    }
    public final function set deepstart(value : float) {
        this.deepstartField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("deep-end") 
    function get deepend() : float {
        return this.deependField;
    }
    public final function set deepend(value : float) {
        this.deependField = value;
    }
    
    ///<remarks/>
    public final function get distortion() : float {
        return this.distortionField;
    }
    public final function set distortion(value : float) {
        this.distortionField = value;
    }
    
    ///<remarks/>
    public final function get smoothness() : float {
        return this.smoothnessField;
    }
    public final function set smoothness(value : float) {
        this.smoothnessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("num-waves") 
    function get numwaves() : float {
        return this.numwavesField;
    }
    public final function set numwaves(value : float) {
        this.numwavesField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("wave-amplitude") 
    function get waveamplitude() : float {
        return this.waveamplitudeField;
    }
    public final function set waveamplitude(value : float) {
        this.waveamplitudeField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("wave-steepness") 
    function get wavesteepness() : float {
        return this.wavesteepnessField;
    }
    public final function set wavesteepness(value : float) {
        this.wavesteepnessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("wave-speed") 
    function get wavespeed() : float {
        return this.wavespeedField;
    }
    public final function set wavespeed(value : float) {
        this.wavespeedField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("wave-length") 
    function get wavelength() : float {
        return this.wavelengthField;
    }
    public final function set wavelength(value : float) {
        this.wavelengthField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("wave-scale") 
    function get wavescale() : float {
        return this.wavescaleField;
    }
    public final function set wavescale(value : float) {
        this.wavescaleField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("wave-intensity") 
    function get waveintensity() : float {
        return this.waveintensityField;
    }
    public final function set waveintensity(value : float) {
        this.waveintensityField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class voxelentity extends entity {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class textentity extends entity {
    
    private var textField : System.String;
    
    private var fontsizeField : float;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get text() : System.String {
        return this.textField;
    }
    public final function set text(value : System.String) {
        this.textField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("font-size") 
    function get fontsize() : float {
        return this.fontsizeField;
    }
    public final function set fontsize(value : float) {
        this.fontsizeField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class terrainentity extends entity {
    
    private var layerField : terrainentitylayer[];
    
    private var layermasksField : System.String;
    
    private var lengthField : double;
    
    private var widthField : double;
    
    private var heightField : double;
    
    private var heightsField : System.String;
    
    private var typeField : System.String;
    
    public function terrainentity() {
        this.typeField = "heightmap";
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("layer") 
    function get layer() : terrainentitylayer[] {
        return this.layerField;
    }
    public final function set layer(value : terrainentitylayer[]) {
        this.layerField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("layer-masks") 
    function get layermasks() : System.String {
        return this.layermasksField;
    }
    public final function set layermasks(value : System.String) {
        this.layermasksField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get length() : double {
        return this.lengthField;
    }
    public final function set length(value : double) {
        this.lengthField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get width() : double {
        return this.widthField;
    }
    public final function set width(value : double) {
        this.widthField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get height() : double {
        return this.heightField;
    }
    public final function set height(value : double) {
        this.heightField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get heights() : System.String {
        return this.heightsField;
    }
    public final function set heights(value : System.String) {
        this.heightsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute("heightmap") 
    function get type() : System.String {
        return this.typeField;
    }
    public final function set type(value : System.String) {
        this.typeField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class lightentity extends entity {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class imageentity extends entity {
    
    private var imagefileField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("image-file") 
    function get imagefile() : System.String {
        return this.imagefileField;
    }
    public final function set imagefile(value : System.String) {
        this.imagefileField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class inputentity extends entity {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class buttonentity extends entity {
    
    private var onclickeventField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("on-click-event") 
    function get onclickevent() : System.String {
        return this.onclickeventField;
    }
    public final function set onclickevent(value : System.String) {
        this.onclickeventField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class htmlentity extends entity {
    
    private var urlField : System.String;
    
    private var onmessageField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get url() : System.String {
        return this.urlField;
    }
    public final function set url(value : System.String) {
        this.urlField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("on-message") 
    function get onmessage() : System.String {
        return this.onmessageField;
    }
    public final function set onmessage(value : System.String) {
        this.onmessageField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class canvasentity extends entity {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class characterentity extends entity {
    
    private var meshnameField : System.String;
    
    private var meshresourceField : System.String[];
    
    private var meshoffsetField : position;
    
    private var meshrotationField : rotation;
    
    private var labeloffsetField : position;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mesh-name") 
    function get meshname() : System.String {
        return this.meshnameField;
    }
    public final function set meshname(value : System.String) {
        this.meshnameField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mesh-resource") 
    function get meshresource() : System.String[] {
        return this.meshresourceField;
    }
    public final function set meshresource(value : System.String[]) {
        this.meshresourceField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mesh-offset") 
    function get meshoffset() : position {
        return this.meshoffsetField;
    }
    public final function set meshoffset(value : position) {
        this.meshoffsetField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mesh-rotation") 
    function get meshrotation() : rotation {
        return this.meshrotationField;
    }
    public final function set meshrotation(value : rotation) {
        this.meshrotationField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("label-offset") 
    function get labeloffset() : position {
        return this.labeloffsetField;
    }
    public final function set labeloffset(value : position) {
        this.labeloffsetField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class archmeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class prismmeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class tetrahedronmeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class rectangularpyramidmeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class conemeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class torusmeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class planemeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class cylindermeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class capsulemeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class spheremeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class cubemeshentity extends entity {
    
    private var colorField : System.String;
    
    ///<remarks/>
    public final function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class meshentity extends entity {
    
    private var meshnameField : System.String;
    
    private var meshresourceField : System.String[];
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mesh-name") 
    function get meshname() : System.String {
        return this.meshnameField;
    }
    public final function set meshname(value : System.String) {
        this.meshnameField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("mesh-resource") 
    function get meshresource() : System.String[] {
        return this.meshresourceField;
    }
    public final function set meshresource(value : System.String[]) {
        this.meshresourceField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class audioentity extends entity {
    
    private var audiofileField : System.String;
    
    private var autoplayField : boolean;
    
    private var loopField : boolean;
    
    private var priorityField : int;
    
    private var volumeField : float;
    
    private var pitchField : float;
    
    private var stereopanField : float;
    
    public function audioentity() {
        this.autoplayField = true;
        this.loopField = true;
        this.priorityField = 0;
        this.volumeField = float(float(1));
        this.pitchField = float(float(0));
        this.stereopanField = float(float(0));
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("audio-file") 
    function get audiofile() : System.String {
        return this.audiofileField;
    }
    public final function set audiofile(value : System.String) {
        this.audiofileField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("auto-play") 
    function get autoplay() : boolean {
        return this.autoplayField;
    }
    public final function set autoplay(value : boolean) {
        this.autoplayField = value;
    }
    
    ///<remarks/>
    public final function get loop() : boolean {
        return this.loopField;
    }
    public final function set loop(value : boolean) {
        this.loopField = value;
    }
    
    ///<remarks/>
    public final function get priority() : int {
        return this.priorityField;
    }
    public final function set priority(value : int) {
        this.priorityField = value;
    }
    
    ///<remarks/>
    public final function get volume() : float {
        return this.volumeField;
    }
    public final function set volume(value : float) {
        this.volumeField = value;
    }
    
    ///<remarks/>
    public final function get pitch() : float {
        return this.pitchField;
    }
    public final function set pitch(value : float) {
        this.pitchField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("stereo-pan") 
    function get stereopan() : float {
        return this.stereopanField;
    }
    public final function set stereopan(value : float) {
        this.stereopanField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class containerentity extends entity {
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(TypeName="lite-fog-settings", Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class litefogsettings {
    
    private var enabledField : boolean;
    
    private var colorField : System.String;
    
    private var densityField : float;
    
    public function litefogsettings() {
        this.enabledField = false;
        this.colorField = "gray";
        this.densityField = float(float(0.5));
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(false) 
    function get enabled() : boolean {
        return this.enabledField;
    }
    public final function set enabled(value : boolean) {
        this.enabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute("gray") 
    function get color() : System.String {
        return this.colorField;
    }
    public final function set color(value : System.String) {
        this.colorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(float, "0.5") 
    function get density() : float {
        return this.densityField;
    }
    public final function set density(value : float) {
        this.densityField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(TypeName="effects-settings", Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class effectssettings {
    
    private var litefogField : litefogsettings;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("lite-fog") 
    function get litefog() : litefogsettings {
        return this.litefogField;
    }
    public final function set litefog(value : litefogsettings) {
        this.litefogField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class liteproceduralsky {
    
    private var sunentitytagField : System.String;
    
    private var daynightcycleenabledField : boolean;
    
    private var groundenabledField : boolean;
    
    private var groundcolorField : System.String;
    
    private var groundheightField : float;
    
    private var groundfadeamountField : float;
    
    private var horizonskyblendField : float;
    
    private var dayhorizoncolorField : System.String;
    
    private var dayskycolorField : System.String;
    
    private var nighthorizoncolorField : System.String;
    
    private var nightskycolorField : System.String;
    
    private var horizonsaturationamountField : float;
    
    private var horizonsaturationfalloffField : float;
    
    private var sunenabledField : boolean;
    
    private var sundiameterField : float;
    
    private var sunhorizoncolorField : System.String;
    
    private var sunzenithcolorField : System.String;
    
    private var sunskylightingenabledField : boolean;
    
    private var skylightingfalloffamountField : float;
    
    private var skylightingfalloffintensityField : float;
    
    private var sunsetintensityField : float;
    
    private var sunsetradialfalloffField : float;
    
    private var sunsethorizontalfalloffField : float;
    
    private var sunsetverticalfalloffField : float;
    
    private var moonenabledField : boolean;
    
    private var moondiameterField : float;
    
    private var mooncolorField : System.String;
    
    private var moonfalloffamountField : float;
    
    private var starsenabledField : boolean;
    
    private var starsbrightnessField : float;
    
    private var starsdaytimebrightnessField : float;
    
    private var starshorizonfalloffField : float;
    
    private var starssaturationField : float;
    
    private var proceduralstarsenabledField : boolean;
    
    private var proceduralstarssharpnessField : float;
    
    private var proceduralstarsamountField : float;
    
    private var starstextureenabledField : boolean;
    
    private var startextureuriField : System.String;
    
    private var startintField : System.String;
    
    private var starscaleField : float;
    
    private var starrotationspeedField : float;
    
    private var cloudsenabledField : boolean;
    
    private var cloudstextureuriField : System.String;
    
    private var cloudsscalexField : float;
    
    private var cloudsscaleyField : float;
    
    private var cloudsspeedxField : float;
    
    private var cloudsspeedyField : float;
    
    private var cloudinessField : float;
    
    private var cloudsopacityField : float;
    
    private var cloudssharpnessField : float;
    
    private var cloudsshadingintensityField : float;
    
    private var cloudszenithfalloffField : float;
    
    private var cloudsiterationsField : int;
    
    private var cloudsgainField : float;
    
    private var cloudslacunarityField : int;
    
    private var cloudsdaycolorField : System.String;
    
    private var cloudsnightcolorField : System.String;
    
    public function liteproceduralsky() {
        this.daynightcycleenabledField = true;
        this.groundenabledField = true;
        this.groundcolorField = "#07070700";
        this.groundheightField = float(float(-0.02));
        this.groundfadeamountField = float(float(0.02));
        this.horizonskyblendField = float(float(0.579));
        this.dayhorizoncolorField = "#448bc5ff";
        this.dayskycolorField = "#08124100";
        this.nighthorizoncolorField = "#07050d00";
        this.nightskycolorField = "03010300";
        this.horizonsaturationamountField = float(float(0.894));
        this.horizonsaturationfalloffField = float(float(4.45));
        this.sunenabledField = true;
        this.sundiameterField = float(float(2));
        this.sunhorizoncolorField = "color(155 72 33 0)";
        this.sunzenithcolorField = "color(158 129 58 0)";
        this.sunskylightingenabledField = true;
        this.skylightingfalloffamountField = float(float(10));
        this.skylightingfalloffintensityField = float(float(1));
        this.sunsetintensityField = float(float(0.3));
        this.sunsetradialfalloffField = float(float(0.1));
        this.sunsethorizontalfalloffField = float(float(0.6));
        this.sunsetverticalfalloffField = float(float(0.5));
        this.moonenabledField = true;
        this.moondiameterField = float(float(2));
        this.mooncolorField = "#abb9bf00";
        this.moonfalloffamountField = float(float(60));
        this.starsenabledField = true;
        this.starsbrightnessField = float(float(0.85));
        this.starsdaytimebrightnessField = float(float(0.1));
        this.starshorizonfalloffField = float(float(0));
        this.starssaturationField = float(float(0.3));
        this.proceduralstarsenabledField = true;
        this.proceduralstarssharpnessField = float(float(1));
        this.proceduralstarsamountField = float(float(1));
        this.starstextureenabledField = true;
        this.startintField = "#ffffff00";
        this.starscaleField = float(float(0.5));
        this.starrotationspeedField = float(float(0.25));
        this.cloudsenabledField = true;
        this.cloudsscalexField = float(float(2));
        this.cloudsscaleyField = float(float(1));
        this.cloudsspeedxField = float(float(0.2));
        this.cloudsspeedyField = float(float(0.3));
        this.cloudinessField = float(float(0.279));
        this.cloudsopacityField = float(float(1));
        this.cloudssharpnessField = float(float(0.8));
        this.cloudsshadingintensityField = float(float(0.8));
        this.cloudszenithfalloffField = float(float(0.339));
        this.cloudsiterationsField = 3;
        this.cloudsgainField = float(float(0.5));
        this.cloudslacunarityField = 2;
        this.cloudsdaycolorField = "#d7dde7";
        this.cloudsnightcolorField = "#7d616f";
        
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sun-entity-tag") 
    function get sunentitytag() : System.String {
        return this.sunentitytagField;
    }
    public final function set sunentitytag(value : System.String) {
        this.sunentitytagField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("day-night-cycle-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get daynightcycleenabled() : boolean {
        return this.daynightcycleenabledField;
    }
    public final function set daynightcycleenabled(value : boolean) {
        this.daynightcycleenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("ground-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get groundenabled() : boolean {
        return this.groundenabledField;
    }
    public final function set groundenabled(value : boolean) {
        this.groundenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("ground-color") System.ComponentModel.DefaultValueAttribute("#07070700") 
    function get groundcolor() : System.String {
        return this.groundcolorField;
    }
    public final function set groundcolor(value : System.String) {
        this.groundcolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("ground-height") System.ComponentModel.DefaultValueAttribute(float, "-0.02") 
    function get groundheight() : float {
        return this.groundheightField;
    }
    public final function set groundheight(value : float) {
        this.groundheightField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("ground-fade-amount") System.ComponentModel.DefaultValueAttribute(float, "0.02") 
    function get groundfadeamount() : float {
        return this.groundfadeamountField;
    }
    public final function set groundfadeamount(value : float) {
        this.groundfadeamountField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("horizon-sky-blend") System.ComponentModel.DefaultValueAttribute(float, "0.579") 
    function get horizonskyblend() : float {
        return this.horizonskyblendField;
    }
    public final function set horizonskyblend(value : float) {
        this.horizonskyblendField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("day-horizon-color") System.ComponentModel.DefaultValueAttribute("#448bc5ff") 
    function get dayhorizoncolor() : System.String {
        return this.dayhorizoncolorField;
    }
    public final function set dayhorizoncolor(value : System.String) {
        this.dayhorizoncolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("day-sky-color") System.ComponentModel.DefaultValueAttribute("#08124100") 
    function get dayskycolor() : System.String {
        return this.dayskycolorField;
    }
    public final function set dayskycolor(value : System.String) {
        this.dayskycolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("night-horizon-color") System.ComponentModel.DefaultValueAttribute("#07050d00") 
    function get nighthorizoncolor() : System.String {
        return this.nighthorizoncolorField;
    }
    public final function set nighthorizoncolor(value : System.String) {
        this.nighthorizoncolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("night-sky-color") System.ComponentModel.DefaultValueAttribute("03010300") 
    function get nightskycolor() : System.String {
        return this.nightskycolorField;
    }
    public final function set nightskycolor(value : System.String) {
        this.nightskycolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("horizon-saturation-amount") System.ComponentModel.DefaultValueAttribute(float, "0.894") 
    function get horizonsaturationamount() : float {
        return this.horizonsaturationamountField;
    }
    public final function set horizonsaturationamount(value : float) {
        this.horizonsaturationamountField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("horizon-saturation-falloff") System.ComponentModel.DefaultValueAttribute(float, "4.45") 
    function get horizonsaturationfalloff() : float {
        return this.horizonsaturationfalloffField;
    }
    public final function set horizonsaturationfalloff(value : float) {
        this.horizonsaturationfalloffField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sun-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get sunenabled() : boolean {
        return this.sunenabledField;
    }
    public final function set sunenabled(value : boolean) {
        this.sunenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sun-diameter") System.ComponentModel.DefaultValueAttribute(float, "2") 
    function get sundiameter() : float {
        return this.sundiameterField;
    }
    public final function set sundiameter(value : float) {
        this.sundiameterField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sun-horizon-color") System.ComponentModel.DefaultValueAttribute("color(155 72 33 0)") 
    function get sunhorizoncolor() : System.String {
        return this.sunhorizoncolorField;
    }
    public final function set sunhorizoncolor(value : System.String) {
        this.sunhorizoncolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sun-zenith-color") System.ComponentModel.DefaultValueAttribute("color(158 129 58 0)") 
    function get sunzenithcolor() : System.String {
        return this.sunzenithcolorField;
    }
    public final function set sunzenithcolor(value : System.String) {
        this.sunzenithcolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sun-sky-lighting-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get sunskylightingenabled() : boolean {
        return this.sunskylightingenabledField;
    }
    public final function set sunskylightingenabled(value : boolean) {
        this.sunskylightingenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sky-lighting-falloff-amount") System.ComponentModel.DefaultValueAttribute(float, "10") 
    function get skylightingfalloffamount() : float {
        return this.skylightingfalloffamountField;
    }
    public final function set skylightingfalloffamount(value : float) {
        this.skylightingfalloffamountField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sky-lighting-falloff-intensity") System.ComponentModel.DefaultValueAttribute(float, "1") 
    function get skylightingfalloffintensity() : float {
        return this.skylightingfalloffintensityField;
    }
    public final function set skylightingfalloffintensity(value : float) {
        this.skylightingfalloffintensityField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sunset-intensity") System.ComponentModel.DefaultValueAttribute(float, "0.3") 
    function get sunsetintensity() : float {
        return this.sunsetintensityField;
    }
    public final function set sunsetintensity(value : float) {
        this.sunsetintensityField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sunset-radial-falloff") System.ComponentModel.DefaultValueAttribute(float, "0.1") 
    function get sunsetradialfalloff() : float {
        return this.sunsetradialfalloffField;
    }
    public final function set sunsetradialfalloff(value : float) {
        this.sunsetradialfalloffField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sunset-horizontal-falloff") System.ComponentModel.DefaultValueAttribute(float, "0.6") 
    function get sunsethorizontalfalloff() : float {
        return this.sunsethorizontalfalloffField;
    }
    public final function set sunsethorizontalfalloff(value : float) {
        this.sunsethorizontalfalloffField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("sunset-vertical-falloff") System.ComponentModel.DefaultValueAttribute(float, "0.5") 
    function get sunsetverticalfalloff() : float {
        return this.sunsetverticalfalloffField;
    }
    public final function set sunsetverticalfalloff(value : float) {
        this.sunsetverticalfalloffField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("moon-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get moonenabled() : boolean {
        return this.moonenabledField;
    }
    public final function set moonenabled(value : boolean) {
        this.moonenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("moon-diameter") System.ComponentModel.DefaultValueAttribute(float, "2") 
    function get moondiameter() : float {
        return this.moondiameterField;
    }
    public final function set moondiameter(value : float) {
        this.moondiameterField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("moon-color") System.ComponentModel.DefaultValueAttribute("#abb9bf00") 
    function get mooncolor() : System.String {
        return this.mooncolorField;
    }
    public final function set mooncolor(value : System.String) {
        this.mooncolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("moon-falloff-amount") System.ComponentModel.DefaultValueAttribute(float, "60") 
    function get moonfalloffamount() : float {
        return this.moonfalloffamountField;
    }
    public final function set moonfalloffamount(value : float) {
        this.moonfalloffamountField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("stars-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get starsenabled() : boolean {
        return this.starsenabledField;
    }
    public final function set starsenabled(value : boolean) {
        this.starsenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("stars-brightness") System.ComponentModel.DefaultValueAttribute(float, "0.85") 
    function get starsbrightness() : float {
        return this.starsbrightnessField;
    }
    public final function set starsbrightness(value : float) {
        this.starsbrightnessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("stars-daytime-brightness") System.ComponentModel.DefaultValueAttribute(float, "0.1") 
    function get starsdaytimebrightness() : float {
        return this.starsdaytimebrightnessField;
    }
    public final function set starsdaytimebrightness(value : float) {
        this.starsdaytimebrightnessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("stars-horizon-falloff") System.ComponentModel.DefaultValueAttribute(float, "0") 
    function get starshorizonfalloff() : float {
        return this.starshorizonfalloffField;
    }
    public final function set starshorizonfalloff(value : float) {
        this.starshorizonfalloffField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("stars-saturation") System.ComponentModel.DefaultValueAttribute(float, "0.3") 
    function get starssaturation() : float {
        return this.starssaturationField;
    }
    public final function set starssaturation(value : float) {
        this.starssaturationField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get proceduralstarsenabled() : boolean {
        return this.proceduralstarsenabledField;
    }
    public final function set proceduralstarsenabled(value : boolean) {
        this.proceduralstarsenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-sharpness") System.ComponentModel.DefaultValueAttribute(float, "1") 
    function get proceduralstarssharpness() : float {
        return this.proceduralstarssharpnessField;
    }
    public final function set proceduralstarssharpness(value : float) {
        this.proceduralstarssharpnessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-amount") System.ComponentModel.DefaultValueAttribute(float, "1") 
    function get proceduralstarsamount() : float {
        return this.proceduralstarsamountField;
    }
    public final function set proceduralstarsamount(value : float) {
        this.proceduralstarsamountField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("stars-texture-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get starstextureenabled() : boolean {
        return this.starstextureenabledField;
    }
    public final function set starstextureenabled(value : boolean) {
        this.starstextureenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("star-texture-uri") 
    function get startextureuri() : System.String {
        return this.startextureuriField;
    }
    public final function set startextureuri(value : System.String) {
        this.startextureuriField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("star-tint") System.ComponentModel.DefaultValueAttribute("#ffffff00") 
    function get startint() : System.String {
        return this.startintField;
    }
    public final function set startint(value : System.String) {
        this.startintField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("star-scale") System.ComponentModel.DefaultValueAttribute(float, "0.5") 
    function get starscale() : float {
        return this.starscaleField;
    }
    public final function set starscale(value : float) {
        this.starscaleField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("star-rotation-speed") System.ComponentModel.DefaultValueAttribute(float, "0.25") 
    function get starrotationspeed() : float {
        return this.starrotationspeedField;
    }
    public final function set starrotationspeed(value : float) {
        this.starrotationspeedField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-enabled") System.ComponentModel.DefaultValueAttribute(true) 
    function get cloudsenabled() : boolean {
        return this.cloudsenabledField;
    }
    public final function set cloudsenabled(value : boolean) {
        this.cloudsenabledField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-texture-uri") 
    function get cloudstextureuri() : System.String {
        return this.cloudstextureuriField;
    }
    public final function set cloudstextureuri(value : System.String) {
        this.cloudstextureuriField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-scale-x") System.ComponentModel.DefaultValueAttribute(float, "2") 
    function get cloudsscalex() : float {
        return this.cloudsscalexField;
    }
    public final function set cloudsscalex(value : float) {
        this.cloudsscalexField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-scale-y") System.ComponentModel.DefaultValueAttribute(float, "1") 
    function get cloudsscaley() : float {
        return this.cloudsscaleyField;
    }
    public final function set cloudsscaley(value : float) {
        this.cloudsscaleyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-speed-x") System.ComponentModel.DefaultValueAttribute(float, "0.2") 
    function get cloudsspeedx() : float {
        return this.cloudsspeedxField;
    }
    public final function set cloudsspeedx(value : float) {
        this.cloudsspeedxField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-speed-y") System.ComponentModel.DefaultValueAttribute(float, "0.3") 
    function get cloudsspeedy() : float {
        return this.cloudsspeedyField;
    }
    public final function set cloudsspeedy(value : float) {
        this.cloudsspeedyField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() System.ComponentModel.DefaultValueAttribute(float, "0.279") 
    function get cloudiness() : float {
        return this.cloudinessField;
    }
    public final function set cloudiness(value : float) {
        this.cloudinessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-opacity") System.ComponentModel.DefaultValueAttribute(float, "1") 
    function get cloudsopacity() : float {
        return this.cloudsopacityField;
    }
    public final function set cloudsopacity(value : float) {
        this.cloudsopacityField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-sharpness") System.ComponentModel.DefaultValueAttribute(float, "0.8") 
    function get cloudssharpness() : float {
        return this.cloudssharpnessField;
    }
    public final function set cloudssharpness(value : float) {
        this.cloudssharpnessField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-shading-intensity") System.ComponentModel.DefaultValueAttribute(float, "0.8") 
    function get cloudsshadingintensity() : float {
        return this.cloudsshadingintensityField;
    }
    public final function set cloudsshadingintensity(value : float) {
        this.cloudsshadingintensityField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-zenith-falloff") System.ComponentModel.DefaultValueAttribute(float, "0.339") 
    function get cloudszenithfalloff() : float {
        return this.cloudszenithfalloffField;
    }
    public final function set cloudszenithfalloff(value : float) {
        this.cloudszenithfalloffField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-iterations") System.ComponentModel.DefaultValueAttribute(3) 
    function get cloudsiterations() : int {
        return this.cloudsiterationsField;
    }
    public final function set cloudsiterations(value : int) {
        this.cloudsiterationsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-gain") System.ComponentModel.DefaultValueAttribute(float, "0.5") 
    function get cloudsgain() : float {
        return this.cloudsgainField;
    }
    public final function set cloudsgain(value : float) {
        this.cloudsgainField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-lacunarity") System.ComponentModel.DefaultValueAttribute(2) 
    function get cloudslacunarity() : int {
        return this.cloudslacunarityField;
    }
    public final function set cloudslacunarity(value : int) {
        this.cloudslacunarityField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-day-color") System.ComponentModel.DefaultValueAttribute("#d7dde7") 
    function get cloudsdaycolor() : System.String {
        return this.cloudsdaycolorField;
    }
    public final function set cloudsdaycolor(value : System.String) {
        this.cloudsdaycolorField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute("clouds-night-color") System.ComponentModel.DefaultValueAttribute("#7d616f") 
    function get cloudsnightcolor() : System.String {
        return this.cloudsnightcolorField;
    }
    public final function set cloudsnightcolor(value : System.String) {
        this.cloudsnightcolorField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class background {
    
    private var itemField : System.Object;
    
    private var itemElementNameField : ItemChoiceType;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("color", System.String) System.Xml.Serialization.XmlElementAttribute("lite-procedural-sky", liteproceduralsky) System.Xml.Serialization.XmlElementAttribute("panorama", System.String) System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName") 
    function get Item() : System.Object {
        return this.itemField;
    }
    public final function set Item(value : System.Object) {
        this.itemField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get ItemElementName() : ItemChoiceType {
        return this.itemElementNameField;
    }
    public final function set ItemElementName(value : ItemChoiceType) {
        this.itemElementNameField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3", IncludeInSchema=false) 
enum ItemChoiceType {
    
    ///<remarks/>
    color,
    
    ///<remarks/>
    liteproceduralsky,
    
    ///<remarks/>
    panorama,
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class synchronizationservice {
    
    private var typeField : System.String;
    
    private var addressField : System.String;
    
    private var idField : System.String;
    
    private var sessionField : System.String;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get type() : System.String {
        return this.typeField;
    }
    public final function set type(value : System.String) {
        this.typeField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get address() : System.String {
        return this.addressField;
    }
    public final function set address(value : System.String) {
        this.addressField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get id() : System.String {
        return this.idField;
    }
    public final function set id(value : System.String) {
        this.idField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlAttributeAttribute() 
    function get session() : System.String {
        return this.sessionField;
    }
    public final function set session(value : System.String) {
        this.sessionField = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class controlflags {
    
    private var leftvrpointerField : System.String;
    
    private var rightvrpointerField : System.String;
    
    private var leftvrpokerField : boolean;
    
    private var leftvrpokerFieldSpecified : boolean;
    
    private var rightvrpokerField : boolean;
    
    private var rightvrpokerFieldSpecified : boolean;
    
    private var lefthandinteractionField : boolean;
    
    private var lefthandinteractionFieldSpecified : boolean;
    
    private var righthandinteractionField : boolean;
    
    private var righthandinteractionFieldSpecified : boolean;
    
    private var turnlocomotionField : System.String;
    
    private var joystickmotionField : boolean;
    
    private var joystickmotionFieldSpecified : boolean;
    
    private var leftgrabmoveField : boolean;
    
    private var leftgrabmoveFieldSpecified : boolean;
    
    private var rightgrabmoveField : boolean;
    
    private var rightgrabmoveFieldSpecified : boolean;
    
    private var twohandedgrabmoveField : boolean;
    
    private var twohandedgrabmoveFieldSpecified : boolean;
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("left-vr-pointer") 
    function get leftvrpointer() : System.String {
        return this.leftvrpointerField;
    }
    public final function set leftvrpointer(value : System.String) {
        this.leftvrpointerField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("right-vr-pointer") 
    function get rightvrpointer() : System.String {
        return this.rightvrpointerField;
    }
    public final function set rightvrpointer(value : System.String) {
        this.rightvrpointerField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("left-vr-poker") 
    function get leftvrpoker() : boolean {
        return this.leftvrpokerField;
    }
    public final function set leftvrpoker(value : boolean) {
        this.leftvrpokerField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get leftvrpokerSpecified() : boolean {
        return this.leftvrpokerFieldSpecified;
    }
    public final function set leftvrpokerSpecified(value : boolean) {
        this.leftvrpokerFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("right-vr-poker") 
    function get rightvrpoker() : boolean {
        return this.rightvrpokerField;
    }
    public final function set rightvrpoker(value : boolean) {
        this.rightvrpokerField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get rightvrpokerSpecified() : boolean {
        return this.rightvrpokerFieldSpecified;
    }
    public final function set rightvrpokerSpecified(value : boolean) {
        this.rightvrpokerFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("left-hand-interaction") 
    function get lefthandinteraction() : boolean {
        return this.lefthandinteractionField;
    }
    public final function set lefthandinteraction(value : boolean) {
        this.lefthandinteractionField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get lefthandinteractionSpecified() : boolean {
        return this.lefthandinteractionFieldSpecified;
    }
    public final function set lefthandinteractionSpecified(value : boolean) {
        this.lefthandinteractionFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("right-hand-interaction") 
    function get righthandinteraction() : boolean {
        return this.righthandinteractionField;
    }
    public final function set righthandinteraction(value : boolean) {
        this.righthandinteractionField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get righthandinteractionSpecified() : boolean {
        return this.righthandinteractionFieldSpecified;
    }
    public final function set righthandinteractionSpecified(value : boolean) {
        this.righthandinteractionFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("turn-locomotion") 
    function get turnlocomotion() : System.String {
        return this.turnlocomotionField;
    }
    public final function set turnlocomotion(value : System.String) {
        this.turnlocomotionField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("joystick-motion") 
    function get joystickmotion() : boolean {
        return this.joystickmotionField;
    }
    public final function set joystickmotion(value : boolean) {
        this.joystickmotionField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get joystickmotionSpecified() : boolean {
        return this.joystickmotionFieldSpecified;
    }
    public final function set joystickmotionSpecified(value : boolean) {
        this.joystickmotionFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("left-grab-move") 
    function get leftgrabmove() : boolean {
        return this.leftgrabmoveField;
    }
    public final function set leftgrabmove(value : boolean) {
        this.leftgrabmoveField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get leftgrabmoveSpecified() : boolean {
        return this.leftgrabmoveFieldSpecified;
    }
    public final function set leftgrabmoveSpecified(value : boolean) {
        this.leftgrabmoveFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("right-grab-move") 
    function get rightgrabmove() : boolean {
        return this.rightgrabmoveField;
    }
    public final function set rightgrabmove(value : boolean) {
        this.rightgrabmoveField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get rightgrabmoveSpecified() : boolean {
        return this.rightgrabmoveFieldSpecified;
    }
    public final function set rightgrabmoveSpecified(value : boolean) {
        this.rightgrabmoveFieldSpecified = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("two-handed-grab-move") 
    function get twohandedgrabmove() : boolean {
        return this.twohandedgrabmoveField;
    }
    public final function set twohandedgrabmove(value : boolean) {
        this.twohandedgrabmoveField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlIgnoreAttribute() 
    function get twohandedgrabmoveSpecified() : boolean {
        return this.twohandedgrabmoveFieldSpecified;
    }
    public final function set twohandedgrabmoveSpecified(value : boolean) {
        this.twohandedgrabmoveFieldSpecified = value;
    }
}

///<remarks/>
public System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0") System.SerializableAttribute() System.Diagnostics.DebuggerStepThroughAttribute() System.ComponentModel.DesignerCategoryAttribute("code") System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.fivesqd.com/schemas/veml/2.3") 
class vemlEnvironment {
    
    private var backgroundField : background;
    
    private var effectsField : effectssettings;
    
    private var entityField : entity[];
    
    ///<remarks/>
    public final function get background() : background {
        return this.backgroundField;
    }
    public final function set background(value : background) {
        this.backgroundField = value;
    }
    
    ///<remarks/>
    public final function get effects() : effectssettings {
        return this.effectsField;
    }
    public final function set effects(value : effectssettings) {
        this.effectsField = value;
    }
    
    ///<remarks/>
    public final System.Xml.Serialization.XmlElementAttribute("entity") 
    function get entity() : entity[] {
        return this.entityField;
    }
    public final function set entity(value : entity[]) {
        this.entityField = value;
    }
}
