'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.8.3928.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4", IsNullable:=false)>  _
Partial Public Class veml
    
    Private metadataField As vemlMetadata
    
    Private environmentField As vemlEnvironment
    
    '''<remarks/>
    Public Property metadata() As vemlMetadata
        Get
            Return Me.metadataField
        End Get
        Set
            Me.metadataField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property environment() As vemlEnvironment
        Get
            Return Me.environmentField
        End Get
        Set
            Me.environmentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class vemlMetadata
    
    Private titleField As String
    
    Private capabilityField() As String
    
    Private scriptField() As String
    
    Private inputeventField() As inputevent
    
    Private controlflagsField As controlflags
    
    Private synchronizationserviceField() As synchronizationservice
    
    '''<remarks/>
    Public Property title() As String
        Get
            Return Me.titleField
        End Get
        Set
            Me.titleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("capability")>  _
    Public Property capability() As String()
        Get
            Return Me.capabilityField
        End Get
        Set
            Me.capabilityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("script")>  _
    Public Property script() As String()
        Get
            Return Me.scriptField
        End Get
        Set
            Me.scriptField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("inputevent")>  _
    Public Property inputevent() As inputevent()
        Get
            Return Me.inputeventField
        End Get
        Set
            Me.inputeventField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property controlflags() As controlflags
        Get
            Return Me.controlflagsField
        End Get
        Set
            Me.controlflagsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("synchronizationservice")>  _
    Public Property synchronizationservice() As synchronizationservice()
        Get
            Return Me.synchronizationserviceField
        End Get
        Set
            Me.synchronizationserviceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class inputevent
    
    Private inputField As String
    
    Private eventField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property input() As String
        Get
            Return Me.inputField
        End Get
        Set
            Me.inputField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property [event]() As String
        Get
            Return Me.eventField
        End Get
        Set
            Me.eventField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class automobileentitywheel
    
    Private wheelsubmeshField As String
    
    Private wheelradiusField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wheel-submesh")>  _
    Public Property wheelsubmesh() As String
        Get
            Return Me.wheelsubmeshField
        End Get
        Set
            Me.wheelsubmeshField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wheel-radius")>  _
    Public Property wheelradius() As Single
        Get
            Return Me.wheelradiusField
        End Get
        Set
            Me.wheelradiusField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class terrainentitylayer
    
    Private diffusetextureField As String
    
    Private normaltextureField As String
    
    Private masktextureField As String
    
    Private specularField As String
    
    Private metallicField As Single
    
    Private smoothnessField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("diffuse-texture")>  _
    Public Property diffusetexture() As String
        Get
            Return Me.diffusetextureField
        End Get
        Set
            Me.diffusetextureField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("normal-texture")>  _
    Public Property normaltexture() As String
        Get
            Return Me.normaltextureField
        End Get
        Set
            Me.normaltextureField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mask-texture")>  _
    Public Property masktexture() As String
        Get
            Return Me.masktextureField
        End Get
        Set
            Me.masktextureField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property specular() As String
        Get
            Return Me.specularField
        End Get
        Set
            Me.specularField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property metallic() As Single
        Get
            Return Me.metallicField
        End Get
        Set
            Me.metallicField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property smoothness() As Single
        Get
            Return Me.smoothnessField
        End Get
        Set
            Me.smoothnessField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class placementsocket
    
    Private positionField As position
    
    Private rotationField As rotation
    
    Private connectingoffsetField As position
    
    '''<remarks/>
    Public Property position() As position
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rotation() As rotation
        Get
            Return Me.rotationField
        End Get
        Set
            Me.rotationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("connecting-offset")>  _
    Public Property connectingoffset() As position
        Get
            Return Me.connectingoffsetField
        End Get
        Set
            Me.connectingoffsetField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class position
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 0R
        Me.yField = 0R
        Me.zField = 0R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class rotation
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Private wField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 0R
        Me.yField = 0R
        Me.zField = 0R
        Me.wField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property w() As Double
        Get
            Return Me.wField
        End Get
        Set
            Me.wField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(TypeName:="size-percent", [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class sizepercent
    
    Private xField As Double
    
    Private yField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 1R
        Me.yField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(TypeName:="position-percent", [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class positionpercent
    
    Private xField As Double
    
    Private yField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 0R
        Me.yField = 0R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class size
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 1R
        Me.yField = 1R
        Me.zField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class scale
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 1R
        Me.yField = 1R
        Me.zField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(canvastransform)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(sizetransform)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(scaletransform)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class basetransform
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class canvastransform
    Inherits basetransform
    
    Private positionpercentField As positionpercent
    
    Private sizepercentField As sizepercent
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("position-percent")>  _
    Public Property positionpercent() As positionpercent
        Get
            Return Me.positionpercentField
        End Get
        Set
            Me.positionpercentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("size-percent")>  _
    Public Property sizepercent() As sizepercent
        Get
            Return Me.sizepercentField
        End Get
        Set
            Me.sizepercentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class sizetransform
    Inherits basetransform
    
    Private positionField As position
    
    Private rotationField As rotation
    
    Private sizeField As size
    
    '''<remarks/>
    Public Property position() As position
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rotation() As rotation
        Get
            Return Me.rotationField
        End Get
        Set
            Me.rotationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property size() As size
        Get
            Return Me.sizeField
        End Get
        Set
            Me.sizeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class scaletransform
    Inherits basetransform
    
    Private positionField As position
    
    Private rotationField As rotation
    
    Private scaleField As scale
    
    '''<remarks/>
    Public Property position() As position
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rotation() As rotation
        Get
            Return Me.rotationField
        End Get
        Set
            Me.rotationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property scale() As scale
        Get
            Return Me.scaleField
        End Get
        Set
            Me.scaleField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(waterblockerentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(airplaneentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(automobileentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(waterentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(voxelentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(textentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(terrainentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(lightentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(imageentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(inputentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(buttonentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(htmlentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(canvasentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(characterentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(archmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(prismmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(tetrahedronmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(rectangularpyramidmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(conemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(torusmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(planemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(cylindermeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(capsulemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(spheremeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(cubemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(meshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(audioentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(containerentity)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class entity
    
    Private transformField As basetransform
    
    Private entity1Field() As entity
    
    Private synchronizerField As String
    
    Private placementsocketField() As placementsocket
    
    Private tagField As String
    
    Private idField As String
    
    Private onloadeventField As String
    
    '''<remarks/>
    Public Property transform() As basetransform
        Get
            Return Me.transformField
        End Get
        Set
            Me.transformField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("entity")>  _
    Public Property entity1() As entity()
        Get
            Return Me.entity1Field
        End Get
        Set
            Me.entity1Field = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property synchronizer() As String
        Get
            Return Me.synchronizerField
        End Get
        Set
            Me.synchronizerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("placement-socket")>  _
    Public Property placementsocket() As placementsocket()
        Get
            Return Me.placementsocketField
        End Get
        Set
            Me.placementsocketField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property tag() As String
        Get
            Return Me.tagField
        End Get
        Set
            Me.tagField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("on-load-event")>  _
    Public Property onloadevent() As String
        Get
            Return Me.onloadeventField
        End Get
        Set
            Me.onloadeventField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class waterblockerentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class airplaneentity
    Inherits entity
    
    Private meshnameField As String
    
    Private meshresourceField() As String
    
    Private massField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-name")>  _
    Public Property meshname() As String
        Get
            Return Me.meshnameField
        End Get
        Set
            Me.meshnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-resource")>  _
    Public Property meshresource() As String()
        Get
            Return Me.meshresourceField
        End Get
        Set
            Me.meshresourceField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property mass() As Single
        Get
            Return Me.massField
        End Get
        Set
            Me.massField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class automobileentity
    Inherits entity
    
    Private meshnameField As String
    
    Private meshresourceField() As String
    
    Private wheelsField() As automobileentitywheel
    
    Private massField As Single
    
    Private automobiletypeField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-name")>  _
    Public Property meshname() As String
        Get
            Return Me.meshnameField
        End Get
        Set
            Me.meshnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-resource")>  _
    Public Property meshresource() As String()
        Get
            Return Me.meshresourceField
        End Get
        Set
            Me.meshresourceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wheels")>  _
    Public Property wheels() As automobileentitywheel()
        Get
            Return Me.wheelsField
        End Get
        Set
            Me.wheelsField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property mass() As Single
        Get
            Return Me.massField
        End Get
        Set
            Me.massField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("automobile-type")>  _
    Public Property automobiletype() As String
        Get
            Return Me.automobiletypeField
        End Get
        Set
            Me.automobiletypeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class waterentity
    Inherits entity
    
    Private shallowcolorField As String
    
    Private deepcolorField As String
    
    Private specularcolorField As String
    
    Private scatteringcolorField As String
    
    Private deepstartField As Single
    
    Private deependField As Single
    
    Private distortionField As Single
    
    Private smoothnessField As Single
    
    Private numwavesField As Single
    
    Private waveamplitudeField As Single
    
    Private wavesteepnessField As Single
    
    Private wavespeedField As Single
    
    Private wavelengthField As Single
    
    Private wavescaleField As Single
    
    Private waveintensityField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("shallow-color")>  _
    Public Property shallowcolor() As String
        Get
            Return Me.shallowcolorField
        End Get
        Set
            Me.shallowcolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("deep-color")>  _
    Public Property deepcolor() As String
        Get
            Return Me.deepcolorField
        End Get
        Set
            Me.deepcolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("specular-color")>  _
    Public Property specularcolor() As String
        Get
            Return Me.specularcolorField
        End Get
        Set
            Me.specularcolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("scattering-color")>  _
    Public Property scatteringcolor() As String
        Get
            Return Me.scatteringcolorField
        End Get
        Set
            Me.scatteringcolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("deep-start")>  _
    Public Property deepstart() As Single
        Get
            Return Me.deepstartField
        End Get
        Set
            Me.deepstartField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("deep-end")>  _
    Public Property deepend() As Single
        Get
            Return Me.deependField
        End Get
        Set
            Me.deependField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property distortion() As Single
        Get
            Return Me.distortionField
        End Get
        Set
            Me.distortionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property smoothness() As Single
        Get
            Return Me.smoothnessField
        End Get
        Set
            Me.smoothnessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("num-waves")>  _
    Public Property numwaves() As Single
        Get
            Return Me.numwavesField
        End Get
        Set
            Me.numwavesField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wave-amplitude")>  _
    Public Property waveamplitude() As Single
        Get
            Return Me.waveamplitudeField
        End Get
        Set
            Me.waveamplitudeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wave-steepness")>  _
    Public Property wavesteepness() As Single
        Get
            Return Me.wavesteepnessField
        End Get
        Set
            Me.wavesteepnessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wave-speed")>  _
    Public Property wavespeed() As Single
        Get
            Return Me.wavespeedField
        End Get
        Set
            Me.wavespeedField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wave-length")>  _
    Public Property wavelength() As Single
        Get
            Return Me.wavelengthField
        End Get
        Set
            Me.wavelengthField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wave-scale")>  _
    Public Property wavescale() As Single
        Get
            Return Me.wavescaleField
        End Get
        Set
            Me.wavescaleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("wave-intensity")>  _
    Public Property waveintensity() As Single
        Get
            Return Me.waveintensityField
        End Get
        Set
            Me.waveintensityField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class voxelentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class textentity
    Inherits entity
    
    Private textField As String
    
    Private fontsizeField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property text() As String
        Get
            Return Me.textField
        End Get
        Set
            Me.textField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("font-size")>  _
    Public Property fontsize() As Single
        Get
            Return Me.fontsizeField
        End Get
        Set
            Me.fontsizeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class terrainentity
    Inherits entity
    
    Private layerField() As terrainentitylayer
    
    Private layermasksField As String
    
    Private lengthField As Double
    
    Private widthField As Double
    
    Private heightField As Double
    
    Private heightsField As String
    
    Private typeField As String
    
    Public Sub New()
        MyBase.New
        Me.typeField = "heightmap"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("layer")>  _
    Public Property layer() As terrainentitylayer()
        Get
            Return Me.layerField
        End Get
        Set
            Me.layerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("layer-masks")>  _
    Public Property layermasks() As String
        Get
            Return Me.layermasksField
        End Get
        Set
            Me.layermasksField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property length() As Double
        Get
            Return Me.lengthField
        End Get
        Set
            Me.lengthField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property width() As Double
        Get
            Return Me.widthField
        End Get
        Set
            Me.widthField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property height() As Double
        Get
            Return Me.heightField
        End Get
        Set
            Me.heightField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property heights() As String
        Get
            Return Me.heightsField
        End Get
        Set
            Me.heightsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute("heightmap")>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class lightentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class imageentity
    Inherits entity
    
    Private imagefileField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("image-file")>  _
    Public Property imagefile() As String
        Get
            Return Me.imagefileField
        End Get
        Set
            Me.imagefileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class inputentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class buttonentity
    Inherits entity
    
    Private onclickeventField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("on-click-event")>  _
    Public Property onclickevent() As String
        Get
            Return Me.onclickeventField
        End Get
        Set
            Me.onclickeventField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class htmlentity
    Inherits entity
    
    Private urlField As String
    
    Private onmessageField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property url() As String
        Get
            Return Me.urlField
        End Get
        Set
            Me.urlField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("on-message")>  _
    Public Property onmessage() As String
        Get
            Return Me.onmessageField
        End Get
        Set
            Me.onmessageField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class canvasentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class characterentity
    Inherits entity
    
    Private meshnameField As String
    
    Private meshresourceField() As String
    
    Private meshoffsetField As position
    
    Private meshrotationField As rotation
    
    Private labeloffsetField As position
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-name")>  _
    Public Property meshname() As String
        Get
            Return Me.meshnameField
        End Get
        Set
            Me.meshnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-resource")>  _
    Public Property meshresource() As String()
        Get
            Return Me.meshresourceField
        End Get
        Set
            Me.meshresourceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-offset")>  _
    Public Property meshoffset() As position
        Get
            Return Me.meshoffsetField
        End Get
        Set
            Me.meshoffsetField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-rotation")>  _
    Public Property meshrotation() As rotation
        Get
            Return Me.meshrotationField
        End Get
        Set
            Me.meshrotationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("label-offset")>  _
    Public Property labeloffset() As position
        Get
            Return Me.labeloffsetField
        End Get
        Set
            Me.labeloffsetField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class archmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class prismmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class tetrahedronmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class rectangularpyramidmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class conemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class torusmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class planemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class cylindermeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class capsulemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class spheremeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class cubemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class meshentity
    Inherits entity
    
    Private meshnameField As String
    
    Private meshresourceField() As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-name")>  _
    Public Property meshname() As String
        Get
            Return Me.meshnameField
        End Get
        Set
            Me.meshnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-resource")>  _
    Public Property meshresource() As String()
        Get
            Return Me.meshresourceField
        End Get
        Set
            Me.meshresourceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class audioentity
    Inherits entity
    
    Private audiofileField As String
    
    Private autoplayField As Boolean
    
    Private loopField As Boolean
    
    Private priorityField As Integer
    
    Private volumeField As Single
    
    Private pitchField As Single
    
    Private stereopanField As Single
    
    Public Sub New()
        MyBase.New
        Me.autoplayField = true
        Me.loopField = true
        Me.priorityField = 0
        Me.volumeField = CType(1!,Single)
        Me.pitchField = CType(0!,Single)
        Me.stereopanField = CType(0!,Single)
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("audio-file")>  _
    Public Property audiofile() As String
        Get
            Return Me.audiofileField
        End Get
        Set
            Me.audiofileField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("auto-play")>  _
    Public Property autoplay() As Boolean
        Get
            Return Me.autoplayField
        End Get
        Set
            Me.autoplayField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property [loop]() As Boolean
        Get
            Return Me.loopField
        End Get
        Set
            Me.loopField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property priority() As Integer
        Get
            Return Me.priorityField
        End Get
        Set
            Me.priorityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property volume() As Single
        Get
            Return Me.volumeField
        End Get
        Set
            Me.volumeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property pitch() As Single
        Get
            Return Me.pitchField
        End Get
        Set
            Me.pitchField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("stereo-pan")>  _
    Public Property stereopan() As Single
        Get
            Return Me.stereopanField
        End Get
        Set
            Me.stereopanField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class containerentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(TypeName:="lite-fog-settings", [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class litefogsettings
    
    Private fogenabledField As Boolean
    
    Private colorField As String
    
    Private densityField As Single
    
    Public Sub New()
        MyBase.New
        Me.fogenabledField = false
        Me.colorField = "gray"
        Me.densityField = CType(0.5!,Single)
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("fog-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(false)>  _
    Public Property fogenabled() As Boolean
        Get
            Return Me.fogenabledField
        End Get
        Set
            Me.fogenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute("gray")>  _
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.5")>  _
    Public Property density() As Single
        Get
            Return Me.densityField
        End Get
        Set
            Me.densityField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(TypeName:="effects-settings", [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class effectssettings
    
    Private litefogField As litefogsettings
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("lite-fog")>  _
    Public Property litefog() As litefogsettings
        Get
            Return Me.litefogField
        End Get
        Set
            Me.litefogField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class liteproceduralsky
    
    Private sunentitytagField As String
    
    Private daynightcycleenabledField As Boolean
    
    Private groundenabledField As Boolean
    
    Private groundcolorField As String
    
    Private groundheightField As Single
    
    Private groundfadeamountField As Single
    
    Private horizonskyblendField As Single
    
    Private dayhorizoncolorField As String
    
    Private dayskycolorField As String
    
    Private nighthorizoncolorField As String
    
    Private nightskycolorField As String
    
    Private horizonsaturationamountField As Single
    
    Private horizonsaturationfalloffField As Single
    
    Private sunenabledField As Boolean
    
    Private sundiameterField As Single
    
    Private sunhorizoncolorField As String
    
    Private sunzenithcolorField As String
    
    Private sunskylightingenabledField As Boolean
    
    Private skylightingfalloffamountField As Single
    
    Private skylightingfalloffintensityField As Single
    
    Private sunsetintensityField As Single
    
    Private sunsetradialfalloffField As Single
    
    Private sunsethorizontalfalloffField As Single
    
    Private sunsetverticalfalloffField As Single
    
    Private moonenabledField As Boolean
    
    Private moondiameterField As Single
    
    Private mooncolorField As String
    
    Private moonfalloffamountField As Single
    
    Private starsenabledField As Boolean
    
    Private starsbrightnessField As Single
    
    Private starsdaytimebrightnessField As Single
    
    Private starshorizonfalloffField As Single
    
    Private starssaturationField As Single
    
    Private proceduralstarsenabledField As Boolean
    
    Private proceduralstarssharpnessField As Single
    
    Private proceduralstarsamountField As Single
    
    Private starstextureenabledField As Boolean
    
    Private startextureuriField As String
    
    Private startintField As String
    
    Private starscaleField As Single
    
    Private starrotationspeedField As Single
    
    Private cloudsenabledField As Boolean
    
    Private cloudstextureuriField As String
    
    Private cloudsscalexField As Single
    
    Private cloudsscaleyField As Single
    
    Private cloudsspeedxField As Single
    
    Private cloudsspeedyField As Single
    
    Private cloudinessField As Single
    
    Private cloudsopacityField As Single
    
    Private cloudssharpnessField As Single
    
    Private cloudsshadingintensityField As Single
    
    Private cloudszenithfalloffField As Single
    
    Private cloudsiterationsField As Integer
    
    Private cloudsgainField As Single
    
    Private cloudslacunarityField As Integer
    
    Private cloudsdaycolorField As String
    
    Private cloudsnightcolorField As String
    
    Public Sub New()
        MyBase.New
        Me.daynightcycleenabledField = true
        Me.groundenabledField = true
        Me.groundcolorField = "#07070700"
        Me.groundheightField = CType(-0.02!,Single)
        Me.groundfadeamountField = CType(0.02!,Single)
        Me.horizonskyblendField = CType(0.579!,Single)
        Me.dayhorizoncolorField = "#448bc5ff"
        Me.dayskycolorField = "#08124100"
        Me.nighthorizoncolorField = "#07050d00"
        Me.nightskycolorField = "03010300"
        Me.horizonsaturationamountField = CType(0.894!,Single)
        Me.horizonsaturationfalloffField = CType(4.45!,Single)
        Me.sunenabledField = true
        Me.sundiameterField = CType(2!,Single)
        Me.sunhorizoncolorField = "color(155 72 33 0)"
        Me.sunzenithcolorField = "color(158 129 58 0)"
        Me.sunskylightingenabledField = true
        Me.skylightingfalloffamountField = CType(10!,Single)
        Me.skylightingfalloffintensityField = CType(1!,Single)
        Me.sunsetintensityField = CType(0.3!,Single)
        Me.sunsetradialfalloffField = CType(0.1!,Single)
        Me.sunsethorizontalfalloffField = CType(0.6!,Single)
        Me.sunsetverticalfalloffField = CType(0.5!,Single)
        Me.moonenabledField = true
        Me.moondiameterField = CType(2!,Single)
        Me.mooncolorField = "#abb9bf00"
        Me.moonfalloffamountField = CType(60!,Single)
        Me.starsenabledField = true
        Me.starsbrightnessField = CType(0.85!,Single)
        Me.starsdaytimebrightnessField = CType(0.1!,Single)
        Me.starshorizonfalloffField = CType(0!,Single)
        Me.starssaturationField = CType(0.3!,Single)
        Me.proceduralstarsenabledField = true
        Me.proceduralstarssharpnessField = CType(1!,Single)
        Me.proceduralstarsamountField = CType(1!,Single)
        Me.starstextureenabledField = true
        Me.startintField = "#ffffff00"
        Me.starscaleField = CType(0.5!,Single)
        Me.starrotationspeedField = CType(0.25!,Single)
        Me.cloudsenabledField = true
        Me.cloudsscalexField = CType(2!,Single)
        Me.cloudsscaleyField = CType(1!,Single)
        Me.cloudsspeedxField = CType(0.2!,Single)
        Me.cloudsspeedyField = CType(0.3!,Single)
        Me.cloudinessField = CType(0.279!,Single)
        Me.cloudsopacityField = CType(1!,Single)
        Me.cloudssharpnessField = CType(0.8!,Single)
        Me.cloudsshadingintensityField = CType(0.8!,Single)
        Me.cloudszenithfalloffField = CType(0.339!,Single)
        Me.cloudsiterationsField = 3
        Me.cloudsgainField = CType(0.5!,Single)
        Me.cloudslacunarityField = 2
        Me.cloudsdaycolorField = "#d7dde7"
        Me.cloudsnightcolorField = "#7d616f"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sun-entity-tag")>  _
    Public Property sunentitytag() As String
        Get
            Return Me.sunentitytagField
        End Get
        Set
            Me.sunentitytagField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("day-night-cycle-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property daynightcycleenabled() As Boolean
        Get
            Return Me.daynightcycleenabledField
        End Get
        Set
            Me.daynightcycleenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("ground-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property groundenabled() As Boolean
        Get
            Return Me.groundenabledField
        End Get
        Set
            Me.groundenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("ground-color"),  _
     System.ComponentModel.DefaultValueAttribute("#07070700")>  _
    Public Property groundcolor() As String
        Get
            Return Me.groundcolorField
        End Get
        Set
            Me.groundcolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("ground-height"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "-0.02")>  _
    Public Property groundheight() As Single
        Get
            Return Me.groundheightField
        End Get
        Set
            Me.groundheightField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("ground-fade-amount"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.02")>  _
    Public Property groundfadeamount() As Single
        Get
            Return Me.groundfadeamountField
        End Get
        Set
            Me.groundfadeamountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("horizon-sky-blend"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.579")>  _
    Public Property horizonskyblend() As Single
        Get
            Return Me.horizonskyblendField
        End Get
        Set
            Me.horizonskyblendField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("day-horizon-color"),  _
     System.ComponentModel.DefaultValueAttribute("#448bc5ff")>  _
    Public Property dayhorizoncolor() As String
        Get
            Return Me.dayhorizoncolorField
        End Get
        Set
            Me.dayhorizoncolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("day-sky-color"),  _
     System.ComponentModel.DefaultValueAttribute("#08124100")>  _
    Public Property dayskycolor() As String
        Get
            Return Me.dayskycolorField
        End Get
        Set
            Me.dayskycolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("night-horizon-color"),  _
     System.ComponentModel.DefaultValueAttribute("#07050d00")>  _
    Public Property nighthorizoncolor() As String
        Get
            Return Me.nighthorizoncolorField
        End Get
        Set
            Me.nighthorizoncolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("night-sky-color"),  _
     System.ComponentModel.DefaultValueAttribute("03010300")>  _
    Public Property nightskycolor() As String
        Get
            Return Me.nightskycolorField
        End Get
        Set
            Me.nightskycolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("horizon-saturation-amount"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.894")>  _
    Public Property horizonsaturationamount() As Single
        Get
            Return Me.horizonsaturationamountField
        End Get
        Set
            Me.horizonsaturationamountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("horizon-saturation-falloff"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "4.45")>  _
    Public Property horizonsaturationfalloff() As Single
        Get
            Return Me.horizonsaturationfalloffField
        End Get
        Set
            Me.horizonsaturationfalloffField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sun-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property sunenabled() As Boolean
        Get
            Return Me.sunenabledField
        End Get
        Set
            Me.sunenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sun-diameter"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "2")>  _
    Public Property sundiameter() As Single
        Get
            Return Me.sundiameterField
        End Get
        Set
            Me.sundiameterField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sun-horizon-color"),  _
     System.ComponentModel.DefaultValueAttribute("color(155 72 33 0)")>  _
    Public Property sunhorizoncolor() As String
        Get
            Return Me.sunhorizoncolorField
        End Get
        Set
            Me.sunhorizoncolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sun-zenith-color"),  _
     System.ComponentModel.DefaultValueAttribute("color(158 129 58 0)")>  _
    Public Property sunzenithcolor() As String
        Get
            Return Me.sunzenithcolorField
        End Get
        Set
            Me.sunzenithcolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sun-sky-lighting-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property sunskylightingenabled() As Boolean
        Get
            Return Me.sunskylightingenabledField
        End Get
        Set
            Me.sunskylightingenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sky-lighting-falloff-amount"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "10")>  _
    Public Property skylightingfalloffamount() As Single
        Get
            Return Me.skylightingfalloffamountField
        End Get
        Set
            Me.skylightingfalloffamountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sky-lighting-falloff-intensity"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "1")>  _
    Public Property skylightingfalloffintensity() As Single
        Get
            Return Me.skylightingfalloffintensityField
        End Get
        Set
            Me.skylightingfalloffintensityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sunset-intensity"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.3")>  _
    Public Property sunsetintensity() As Single
        Get
            Return Me.sunsetintensityField
        End Get
        Set
            Me.sunsetintensityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sunset-radial-falloff"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.1")>  _
    Public Property sunsetradialfalloff() As Single
        Get
            Return Me.sunsetradialfalloffField
        End Get
        Set
            Me.sunsetradialfalloffField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sunset-horizontal-falloff"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.6")>  _
    Public Property sunsethorizontalfalloff() As Single
        Get
            Return Me.sunsethorizontalfalloffField
        End Get
        Set
            Me.sunsethorizontalfalloffField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("sunset-vertical-falloff"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.5")>  _
    Public Property sunsetverticalfalloff() As Single
        Get
            Return Me.sunsetverticalfalloffField
        End Get
        Set
            Me.sunsetverticalfalloffField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("moon-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property moonenabled() As Boolean
        Get
            Return Me.moonenabledField
        End Get
        Set
            Me.moonenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("moon-diameter"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "2")>  _
    Public Property moondiameter() As Single
        Get
            Return Me.moondiameterField
        End Get
        Set
            Me.moondiameterField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("moon-color"),  _
     System.ComponentModel.DefaultValueAttribute("#abb9bf00")>  _
    Public Property mooncolor() As String
        Get
            Return Me.mooncolorField
        End Get
        Set
            Me.mooncolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("moon-falloff-amount"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "60")>  _
    Public Property moonfalloffamount() As Single
        Get
            Return Me.moonfalloffamountField
        End Get
        Set
            Me.moonfalloffamountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("stars-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property starsenabled() As Boolean
        Get
            Return Me.starsenabledField
        End Get
        Set
            Me.starsenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("stars-brightness"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.85")>  _
    Public Property starsbrightness() As Single
        Get
            Return Me.starsbrightnessField
        End Get
        Set
            Me.starsbrightnessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("stars-daytime-brightness"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.1")>  _
    Public Property starsdaytimebrightness() As Single
        Get
            Return Me.starsdaytimebrightnessField
        End Get
        Set
            Me.starsdaytimebrightnessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("stars-horizon-falloff"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0")>  _
    Public Property starshorizonfalloff() As Single
        Get
            Return Me.starshorizonfalloffField
        End Get
        Set
            Me.starshorizonfalloffField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("stars-saturation"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.3")>  _
    Public Property starssaturation() As Single
        Get
            Return Me.starssaturationField
        End Get
        Set
            Me.starssaturationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property proceduralstarsenabled() As Boolean
        Get
            Return Me.proceduralstarsenabledField
        End Get
        Set
            Me.proceduralstarsenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-sharpness"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "1")>  _
    Public Property proceduralstarssharpness() As Single
        Get
            Return Me.proceduralstarssharpnessField
        End Get
        Set
            Me.proceduralstarssharpnessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("procedural-stars-amount"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "1")>  _
    Public Property proceduralstarsamount() As Single
        Get
            Return Me.proceduralstarsamountField
        End Get
        Set
            Me.proceduralstarsamountField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("stars-texture-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property starstextureenabled() As Boolean
        Get
            Return Me.starstextureenabledField
        End Get
        Set
            Me.starstextureenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("star-texture-uri")>  _
    Public Property startextureuri() As String
        Get
            Return Me.startextureuriField
        End Get
        Set
            Me.startextureuriField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("star-tint"),  _
     System.ComponentModel.DefaultValueAttribute("#ffffff00")>  _
    Public Property startint() As String
        Get
            Return Me.startintField
        End Get
        Set
            Me.startintField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("star-scale"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.5")>  _
    Public Property starscale() As Single
        Get
            Return Me.starscaleField
        End Get
        Set
            Me.starscaleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("star-rotation-speed"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.25")>  _
    Public Property starrotationspeed() As Single
        Get
            Return Me.starrotationspeedField
        End Get
        Set
            Me.starrotationspeedField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-enabled"),  _
     System.ComponentModel.DefaultValueAttribute(true)>  _
    Public Property cloudsenabled() As Boolean
        Get
            Return Me.cloudsenabledField
        End Get
        Set
            Me.cloudsenabledField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-texture-uri")>  _
    Public Property cloudstextureuri() As String
        Get
            Return Me.cloudstextureuriField
        End Get
        Set
            Me.cloudstextureuriField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-scale-x"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "2")>  _
    Public Property cloudsscalex() As Single
        Get
            Return Me.cloudsscalexField
        End Get
        Set
            Me.cloudsscalexField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-scale-y"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "1")>  _
    Public Property cloudsscaley() As Single
        Get
            Return Me.cloudsscaleyField
        End Get
        Set
            Me.cloudsscaleyField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-speed-x"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.2")>  _
    Public Property cloudsspeedx() As Single
        Get
            Return Me.cloudsspeedxField
        End Get
        Set
            Me.cloudsspeedxField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-speed-y"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.3")>  _
    Public Property cloudsspeedy() As Single
        Get
            Return Me.cloudsspeedyField
        End Get
        Set
            Me.cloudsspeedyField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.279")>  _
    Public Property cloudiness() As Single
        Get
            Return Me.cloudinessField
        End Get
        Set
            Me.cloudinessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-opacity"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "1")>  _
    Public Property cloudsopacity() As Single
        Get
            Return Me.cloudsopacityField
        End Get
        Set
            Me.cloudsopacityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-sharpness"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.8")>  _
    Public Property cloudssharpness() As Single
        Get
            Return Me.cloudssharpnessField
        End Get
        Set
            Me.cloudssharpnessField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-shading-intensity"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.8")>  _
    Public Property cloudsshadingintensity() As Single
        Get
            Return Me.cloudsshadingintensityField
        End Get
        Set
            Me.cloudsshadingintensityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-zenith-falloff"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.339")>  _
    Public Property cloudszenithfalloff() As Single
        Get
            Return Me.cloudszenithfalloffField
        End Get
        Set
            Me.cloudszenithfalloffField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-iterations"),  _
     System.ComponentModel.DefaultValueAttribute(3)>  _
    Public Property cloudsiterations() As Integer
        Get
            Return Me.cloudsiterationsField
        End Get
        Set
            Me.cloudsiterationsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-gain"),  _
     System.ComponentModel.DefaultValueAttribute(GetType(Single), "0.5")>  _
    Public Property cloudsgain() As Single
        Get
            Return Me.cloudsgainField
        End Get
        Set
            Me.cloudsgainField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-lacunarity"),  _
     System.ComponentModel.DefaultValueAttribute(2)>  _
    Public Property cloudslacunarity() As Integer
        Get
            Return Me.cloudslacunarityField
        End Get
        Set
            Me.cloudslacunarityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-day-color"),  _
     System.ComponentModel.DefaultValueAttribute("#d7dde7")>  _
    Public Property cloudsdaycolor() As String
        Get
            Return Me.cloudsdaycolorField
        End Get
        Set
            Me.cloudsdaycolorField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("clouds-night-color"),  _
     System.ComponentModel.DefaultValueAttribute("#7d616f")>  _
    Public Property cloudsnightcolor() As String
        Get
            Return Me.cloudsnightcolorField
        End Get
        Set
            Me.cloudsnightcolorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class background
    
    Private itemField As Object
    
    Private itemElementNameField As ItemChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("color", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("lite-procedural-sky", GetType(liteproceduralsky)),  _
     System.Xml.Serialization.XmlElementAttribute("panorama", GetType(String)),  _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
    Public Property Item() As Object
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemElementName() As ItemChoiceType
        Get
            Return Me.itemElementNameField
        End Get
        Set
            Me.itemElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4", IncludeInSchema:=false)>  _
Public Enum ItemChoiceType
    
    '''<remarks/>
    color
    
    '''<remarks/>
    <System.Xml.Serialization.XmlEnumAttribute("lite-procedural-sky")>  _
    liteproceduralsky
    
    '''<remarks/>
    panorama
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class synchronizationservice
    
    Private typeField As String
    
    Private addressField As String
    
    Private idField As String
    
    Private sessionField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property address() As String
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property session() As String
        Get
            Return Me.sessionField
        End Get
        Set
            Me.sessionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class controlflags
    
    Private leftvrpointerField As String
    
    Private rightvrpointerField As String
    
    Private leftvrpokerField As Boolean
    
    Private leftvrpokerFieldSpecified As Boolean
    
    Private rightvrpokerField As Boolean
    
    Private rightvrpokerFieldSpecified As Boolean
    
    Private lefthandinteractionField As Boolean
    
    Private lefthandinteractionFieldSpecified As Boolean
    
    Private righthandinteractionField As Boolean
    
    Private righthandinteractionFieldSpecified As Boolean
    
    Private turnlocomotionField As String
    
    Private joystickmotionField As Boolean
    
    Private joystickmotionFieldSpecified As Boolean
    
    Private leftgrabmoveField As Boolean
    
    Private leftgrabmoveFieldSpecified As Boolean
    
    Private rightgrabmoveField As Boolean
    
    Private rightgrabmoveFieldSpecified As Boolean
    
    Private twohandedgrabmoveField As Boolean
    
    Private twohandedgrabmoveFieldSpecified As Boolean
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("left-vr-pointer")>  _
    Public Property leftvrpointer() As String
        Get
            Return Me.leftvrpointerField
        End Get
        Set
            Me.leftvrpointerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("right-vr-pointer")>  _
    Public Property rightvrpointer() As String
        Get
            Return Me.rightvrpointerField
        End Get
        Set
            Me.rightvrpointerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("left-vr-poker")>  _
    Public Property leftvrpoker() As Boolean
        Get
            Return Me.leftvrpokerField
        End Get
        Set
            Me.leftvrpokerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property leftvrpokerSpecified() As Boolean
        Get
            Return Me.leftvrpokerFieldSpecified
        End Get
        Set
            Me.leftvrpokerFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("right-vr-poker")>  _
    Public Property rightvrpoker() As Boolean
        Get
            Return Me.rightvrpokerField
        End Get
        Set
            Me.rightvrpokerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property rightvrpokerSpecified() As Boolean
        Get
            Return Me.rightvrpokerFieldSpecified
        End Get
        Set
            Me.rightvrpokerFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("left-hand-interaction")>  _
    Public Property lefthandinteraction() As Boolean
        Get
            Return Me.lefthandinteractionField
        End Get
        Set
            Me.lefthandinteractionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property lefthandinteractionSpecified() As Boolean
        Get
            Return Me.lefthandinteractionFieldSpecified
        End Get
        Set
            Me.lefthandinteractionFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("right-hand-interaction")>  _
    Public Property righthandinteraction() As Boolean
        Get
            Return Me.righthandinteractionField
        End Get
        Set
            Me.righthandinteractionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property righthandinteractionSpecified() As Boolean
        Get
            Return Me.righthandinteractionFieldSpecified
        End Get
        Set
            Me.righthandinteractionFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("turn-locomotion")>  _
    Public Property turnlocomotion() As String
        Get
            Return Me.turnlocomotionField
        End Get
        Set
            Me.turnlocomotionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("joystick-motion")>  _
    Public Property joystickmotion() As Boolean
        Get
            Return Me.joystickmotionField
        End Get
        Set
            Me.joystickmotionField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property joystickmotionSpecified() As Boolean
        Get
            Return Me.joystickmotionFieldSpecified
        End Get
        Set
            Me.joystickmotionFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("left-grab-move")>  _
    Public Property leftgrabmove() As Boolean
        Get
            Return Me.leftgrabmoveField
        End Get
        Set
            Me.leftgrabmoveField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property leftgrabmoveSpecified() As Boolean
        Get
            Return Me.leftgrabmoveFieldSpecified
        End Get
        Set
            Me.leftgrabmoveFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("right-grab-move")>  _
    Public Property rightgrabmove() As Boolean
        Get
            Return Me.rightgrabmoveField
        End Get
        Set
            Me.rightgrabmoveField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property rightgrabmoveSpecified() As Boolean
        Get
            Return Me.rightgrabmoveFieldSpecified
        End Get
        Set
            Me.rightgrabmoveFieldSpecified = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("two-handed-grab-move")>  _
    Public Property twohandedgrabmove() As Boolean
        Get
            Return Me.twohandedgrabmoveField
        End Get
        Set
            Me.twohandedgrabmoveField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property twohandedgrabmoveSpecified() As Boolean
        Get
            Return Me.twohandedgrabmoveFieldSpecified
        End Get
        Set
            Me.twohandedgrabmoveFieldSpecified = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.fivesqd.com/schemas/veml/2.4")>  _
Partial Public Class vemlEnvironment
    
    Private backgroundField As background
    
    Private effectsField As effectssettings
    
    Private entityField() As entity
    
    '''<remarks/>
    Public Property background() As background
        Get
            Return Me.backgroundField
        End Get
        Set
            Me.backgroundField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property effects() As effectssettings
        Get
            Return Me.effectsField
        End Get
        Set
            Me.effectsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("entity")>  _
    Public Property entity() As entity()
        Get
            Return Me.entityField
        End Get
        Set
            Me.entityField = value
        End Set
    End Property
End Class
