'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.8.3928.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.fivesqd.com/schemas/veml/2.0"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0", IsNullable:=false)>  _
Partial Public Class veml
    
    Private metadataField As vemlMetadata
    
    Private environmentField As vemlEnvironment
    
    '''<remarks/>
    Public Property metadata() As vemlMetadata
        Get
            Return Me.metadataField
        End Get
        Set
            Me.metadataField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property environment() As vemlEnvironment
        Get
            Return Me.environmentField
        End Get
        Set
            Me.environmentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class vemlMetadata
    
    Private titleField As String
    
    Private capabilityField() As String
    
    Private scriptField() As String
    
    Private inputeventField() As inputevent
    
    Private synchronizationserviceField() As synchronizationservice
    
    '''<remarks/>
    Public Property title() As String
        Get
            Return Me.titleField
        End Get
        Set
            Me.titleField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("capability")>  _
    Public Property capability() As String()
        Get
            Return Me.capabilityField
        End Get
        Set
            Me.capabilityField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("script")>  _
    Public Property script() As String()
        Get
            Return Me.scriptField
        End Get
        Set
            Me.scriptField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("inputevent")>  _
    Public Property inputevent() As inputevent()
        Get
            Return Me.inputeventField
        End Get
        Set
            Me.inputeventField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("synchronizationservice")>  _
    Public Property synchronizationservice() As synchronizationservice()
        Get
            Return Me.synchronizationserviceField
        End Get
        Set
            Me.synchronizationserviceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class inputevent
    
    Private inputField As String
    
    Private eventField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property input() As String
        Get
            Return Me.inputField
        End Get
        Set
            Me.inputField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property [event]() As String
        Get
            Return Me.eventField
        End Get
        Set
            Me.eventField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class terrainentitylayer
    
    Private diffusetextureField As String
    
    Private normaltextureField As String
    
    Private masktextureField As String
    
    Private specularField As String
    
    Private metallicField As Single
    
    Private smoothnessField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("diffuse-texture")>  _
    Public Property diffusetexture() As String
        Get
            Return Me.diffusetextureField
        End Get
        Set
            Me.diffusetextureField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("normal-texture")>  _
    Public Property normaltexture() As String
        Get
            Return Me.normaltextureField
        End Get
        Set
            Me.normaltextureField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mask-texture")>  _
    Public Property masktexture() As String
        Get
            Return Me.masktextureField
        End Get
        Set
            Me.masktextureField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property specular() As String
        Get
            Return Me.specularField
        End Get
        Set
            Me.specularField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property metallic() As Single
        Get
            Return Me.metallicField
        End Get
        Set
            Me.metallicField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property smoothness() As Single
        Get
            Return Me.smoothnessField
        End Get
        Set
            Me.smoothnessField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class placementsocket
    
    Private positionField As position
    
    Private rotationField As rotation
    
    Private connectingoffsetField As position
    
    '''<remarks/>
    Public Property position() As position
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rotation() As rotation
        Get
            Return Me.rotationField
        End Get
        Set
            Me.rotationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("connecting-offset")>  _
    Public Property connectingoffset() As position
        Get
            Return Me.connectingoffsetField
        End Get
        Set
            Me.connectingoffsetField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class position
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 0R
        Me.yField = 0R
        Me.zField = 0R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class rotation
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Private wField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 0R
        Me.yField = 0R
        Me.zField = 0R
        Me.wField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property w() As Double
        Get
            Return Me.wField
        End Get
        Set
            Me.wField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(TypeName:="size-percent", [Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class sizepercent
    
    Private xField As Double
    
    Private yField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 1R
        Me.yField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(TypeName:="position-percent", [Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class positionpercent
    
    Private xField As Double
    
    Private yField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 0R
        Me.yField = 0R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(0R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class size
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 1R
        Me.yField = 1R
        Me.zField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class scale
    
    Private xField As Double
    
    Private yField As Double
    
    Private zField As Double
    
    Public Sub New()
        MyBase.New
        Me.xField = 1R
        Me.yField = 1R
        Me.zField = 1R
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property x() As Double
        Get
            Return Me.xField
        End Get
        Set
            Me.xField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property y() As Double
        Get
            Return Me.yField
        End Get
        Set
            Me.yField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute(1R)>  _
    Public Property z() As Double
        Get
            Return Me.zField
        End Get
        Set
            Me.zField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(canvastransform)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(sizetransform)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(scaletransform)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class basetransform
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class canvastransform
    Inherits basetransform
    
    Private positionpercentField As positionpercent
    
    Private sizepercentField As sizepercent
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("position-percent")>  _
    Public Property positionpercent() As positionpercent
        Get
            Return Me.positionpercentField
        End Get
        Set
            Me.positionpercentField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("size-percent")>  _
    Public Property sizepercent() As sizepercent
        Get
            Return Me.sizepercentField
        End Get
        Set
            Me.sizepercentField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class sizetransform
    Inherits basetransform
    
    Private positionField As position
    
    Private rotationField As rotation
    
    Private sizeField As size
    
    '''<remarks/>
    Public Property position() As position
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rotation() As rotation
        Get
            Return Me.rotationField
        End Get
        Set
            Me.rotationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property size() As size
        Get
            Return Me.sizeField
        End Get
        Set
            Me.sizeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class scaletransform
    Inherits basetransform
    
    Private positionField As position
    
    Private rotationField As rotation
    
    Private scaleField As scale
    
    '''<remarks/>
    Public Property position() As position
        Get
            Return Me.positionField
        End Get
        Set
            Me.positionField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property rotation() As rotation
        Get
            Return Me.rotationField
        End Get
        Set
            Me.rotationField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property scale() As scale
        Get
            Return Me.scaleField
        End Get
        Set
            Me.scaleField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.Xml.Serialization.XmlIncludeAttribute(GetType(voxelentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(textentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(terrainentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(lightentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(imageentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(inputentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(buttonentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(htmlentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(canvasentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(characterentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(archmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(prismmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(tetrahedronmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(rectangularpyramidmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(conemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(torusmeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(planemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(cylindermeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(capsulemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(spheremeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(cubemeshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(meshentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(audioentity)),  _
 System.Xml.Serialization.XmlIncludeAttribute(GetType(containerentity)),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class entity
    
    Private transformField As basetransform
    
    Private entity1Field() As entity
    
    Private synchronizerField As String
    
    Private placementsocketField() As placementsocket
    
    Private tagField As String
    
    Private idField As String
    
    Private onloadeventField As String
    
    '''<remarks/>
    Public Property transform() As basetransform
        Get
            Return Me.transformField
        End Get
        Set
            Me.transformField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("entity")>  _
    Public Property entity1() As entity()
        Get
            Return Me.entity1Field
        End Get
        Set
            Me.entity1Field = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property synchronizer() As String
        Get
            Return Me.synchronizerField
        End Get
        Set
            Me.synchronizerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("placement-socket")>  _
    Public Property placementsocket() As placementsocket()
        Get
            Return Me.placementsocketField
        End Get
        Set
            Me.placementsocketField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property tag() As String
        Get
            Return Me.tagField
        End Get
        Set
            Me.tagField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("on-load-event")>  _
    Public Property onloadevent() As String
        Get
            Return Me.onloadeventField
        End Get
        Set
            Me.onloadeventField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class voxelentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class textentity
    Inherits entity
    
    Private textField As String
    
    Private fontsizeField As Single
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property text() As String
        Get
            Return Me.textField
        End Get
        Set
            Me.textField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("font-size")>  _
    Public Property fontsize() As Single
        Get
            Return Me.fontsizeField
        End Get
        Set
            Me.fontsizeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class terrainentity
    Inherits entity
    
    Private layerField() As terrainentitylayer
    
    Private layermasksField As String
    
    Private lengthField As Double
    
    Private widthField As Double
    
    Private heightField As Double
    
    Private heightsField As String
    
    Private typeField As String
    
    Public Sub New()
        MyBase.New
        Me.typeField = "heightmap"
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("layer")>  _
    Public Property layer() As terrainentitylayer()
        Get
            Return Me.layerField
        End Get
        Set
            Me.layerField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("layer-masks")>  _
    Public Property layermasks() As String
        Get
            Return Me.layermasksField
        End Get
        Set
            Me.layermasksField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property length() As Double
        Get
            Return Me.lengthField
        End Get
        Set
            Me.lengthField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property width() As Double
        Get
            Return Me.widthField
        End Get
        Set
            Me.widthField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property height() As Double
        Get
            Return Me.heightField
        End Get
        Set
            Me.heightField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property heights() As String
        Get
            Return Me.heightsField
        End Get
        Set
            Me.heightsField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute(),  _
     System.ComponentModel.DefaultValueAttribute("heightmap")>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class lightentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class imageentity
    Inherits entity
    
    Private imagefileField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("image-file")>  _
    Public Property imagefile() As String
        Get
            Return Me.imagefileField
        End Get
        Set
            Me.imagefileField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class inputentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class buttonentity
    Inherits entity
    
    Private onclickeventField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("on-click-event")>  _
    Public Property onclickevent() As String
        Get
            Return Me.onclickeventField
        End Get
        Set
            Me.onclickeventField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class htmlentity
    Inherits entity
    
    Private urlField As String
    
    Private onmessageField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property url() As String
        Get
            Return Me.urlField
        End Get
        Set
            Me.urlField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute("on-message")>  _
    Public Property onmessage() As String
        Get
            Return Me.onmessageField
        End Get
        Set
            Me.onmessageField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class canvasentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class characterentity
    Inherits entity
    
    Private meshnameField As String
    
    Private meshresourceField() As String
    
    Private meshoffsetField As position
    
    Private meshrotationField As rotation
    
    Private labeloffsetField As position
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-name")>  _
    Public Property meshname() As String
        Get
            Return Me.meshnameField
        End Get
        Set
            Me.meshnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-resource")>  _
    Public Property meshresource() As String()
        Get
            Return Me.meshresourceField
        End Get
        Set
            Me.meshresourceField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-offset")>  _
    Public Property meshoffset() As position
        Get
            Return Me.meshoffsetField
        End Get
        Set
            Me.meshoffsetField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-rotation")>  _
    Public Property meshrotation() As rotation
        Get
            Return Me.meshrotationField
        End Get
        Set
            Me.meshrotationField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("label-offset")>  _
    Public Property labeloffset() As position
        Get
            Return Me.labeloffsetField
        End Get
        Set
            Me.labeloffsetField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class archmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class prismmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class tetrahedronmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class rectangularpyramidmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class conemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class torusmeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class planemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class cylindermeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class capsulemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class spheremeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class cubemeshentity
    Inherits entity
    
    Private colorField As String
    
    '''<remarks/>
    Public Property color() As String
        Get
            Return Me.colorField
        End Get
        Set
            Me.colorField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class meshentity
    Inherits entity
    
    Private meshnameField As String
    
    Private meshresourceField() As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-name")>  _
    Public Property meshname() As String
        Get
            Return Me.meshnameField
        End Get
        Set
            Me.meshnameField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("mesh-resource")>  _
    Public Property meshresource() As String()
        Get
            Return Me.meshresourceField
        End Get
        Set
            Me.meshresourceField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class audioentity
    Inherits entity
    
    Private audiofileField As String
    
    Private autoplayField As Boolean
    
    Private loopField As Boolean
    
    Private priorityField As Integer
    
    Private volumeField As Single
    
    Private pitchField As Single
    
    Private stereopanField As Single
    
    Public Sub New()
        MyBase.New
        Me.autoplayField = true
        Me.loopField = true
        Me.priorityField = 0
        Me.volumeField = CType(1!,Single)
        Me.pitchField = CType(0!,Single)
        Me.stereopanField = CType(0!,Single)
    End Sub
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("audio-file")>  _
    Public Property audiofile() As String
        Get
            Return Me.audiofileField
        End Get
        Set
            Me.audiofileField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("auto-play")>  _
    Public Property autoplay() As Boolean
        Get
            Return Me.autoplayField
        End Get
        Set
            Me.autoplayField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property [loop]() As Boolean
        Get
            Return Me.loopField
        End Get
        Set
            Me.loopField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property priority() As Integer
        Get
            Return Me.priorityField
        End Get
        Set
            Me.priorityField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property volume() As Single
        Get
            Return Me.volumeField
        End Get
        Set
            Me.volumeField = value
        End Set
    End Property
    
    '''<remarks/>
    Public Property pitch() As Single
        Get
            Return Me.pitchField
        End Get
        Set
            Me.pitchField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("stereo-pan")>  _
    Public Property stereopan() As Single
        Get
            Return Me.stereopanField
        End Get
        Set
            Me.stereopanField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class containerentity
    Inherits entity
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class background
    
    Private itemField As String
    
    Private itemElementNameField As ItemChoiceType
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("color", GetType(String)),  _
     System.Xml.Serialization.XmlElementAttribute("panorama", GetType(String)),  _
     System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
    Public Property Item() As String
        Get
            Return Me.itemField
        End Get
        Set
            Me.itemField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ItemElementName() As ItemChoiceType
        Get
            Return Me.itemElementNameField
        End Get
        Set
            Me.itemElementNameField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0", IncludeInSchema:=false)>  _
Public Enum ItemChoiceType
    
    '''<remarks/>
    color
    
    '''<remarks/>
    panorama
End Enum

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class synchronizationservice
    
    Private typeField As String
    
    Private addressField As String
    
    Private idField As String
    
    Private sessionField As String
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property type() As String
        Get
            Return Me.typeField
        End Get
        Set
            Me.typeField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property address() As String
        Get
            Return Me.addressField
        End Get
        Set
            Me.addressField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property id() As String
        Get
            Return Me.idField
        End Get
        Set
            Me.idField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property session() As String
        Get
            Return Me.sessionField
        End Get
        Set
            Me.sessionField = value
        End Set
    End Property
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.fivesqd.com/schemas/veml/2.0")>  _
Partial Public Class vemlEnvironment
    
    Private backgroundField As background
    
    Private entityField() As entity
    
    '''<remarks/>
    Public Property background() As background
        Get
            Return Me.backgroundField
        End Get
        Set
            Me.backgroundField = value
        End Set
    End Property
    
    '''<remarks/>
    <System.Xml.Serialization.XmlElementAttribute("entity")>  _
    Public Property entity() As entity()
        Get
            Return Me.entityField
        End Get
        Set
            Me.entityField = value
        End Set
    End Property
End Class
